name: 🚀 Flexiroam automation service v1.0

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: false

      - name: 🚀 Initializing Flexiroam automation service v1.0
        run: python main.py
        env:
          ENV_USR_EMAIL: ${{ secrets.ENV_USR_EMAIL }}
          ENV_USR_PASS: ${{ secrets.ENV_USR_PASS }}
          ENV_REPO_OWNER: ${{ secrets.ENV_REPO_OWNER }}
          ENV_REPO_NAME: ${{ secrets.ENV_REPO_NAME }}
          ENV_GIT_TOKEN: ${{ secrets.ENV_GIT_TOKEN }}
